pressure:
  ###############
  # template:
    # location: str, REQUIRED
        # enter the location name of the pressure measurements
      # raw_pressure_folder: str, REQUIRED
        # full path of the raw pressure data
      # raw_file_extension: str, REQUIRED
        # the extension of raw data files
        # do not enter a dot before the extension
      # parsed_pressure_folder: str, REQUIRED
        # full path of the parsed pressure data
      # use_pressure_correction_factor: bool, OPTIONAL
        # True to calibrate the pressure to the em27 instrument elevation
      # em27_m: int | float | str, OPTIONAL
        # The elevation above sea level of the mirrors of em27 instrument in meters
      # pressure_sensor_m: int | float | str, OPTIONAL
        # The elevation above sea level of the pressure sensor in meters
      # start_date: str, yyyy-mm-dd, REQUIRED
        # first date to parse
      # end_date: str, yyyy-mm-dd, OPTIONAL
        # last date to parse, OPTIONAL, default is yesterday
  ###############
  # to skip processing a location, comment out the lines
  ###############
  location1:
    raw_pressure_folder: "examples/pressure/location1_raw"
    raw_file_extension: "txt"
    parsed_pressure_folder: "examples/pressure/location1_processed"
    use_pressure_correction_factor: True
    em27_m: 181
    pressure_sensor_m: 181
    start_date: "2016-06-02"
    end_date:
  location2:
    raw_pressure_folder: "examples/pressure/location2_raw_collected"
    # this folder contains symlinks and is generated for running tests
    # see symlinks section
    raw_file_extension: "lst"
    use_pressure_correction_factor: True
    em27_m: 180
    pressure_sensor_m: 180
    parsed_pressure_folder: "examples/pressure/location2_processed"
    start_date: "2016-06-02"
    end_date:

symlinks:
  ###############
  # template:
    # job: str, REQUIRED
        # enter a name for the job
      # target_folders: list of str, REQUIRED
        # targets are the items that links point to
      # link_folder: str, REQUIRED
        # links point to targets
  ###############
  # to skip processing a job, comment out the lines
  ###############
  job1:
    target_folders:
      - "examples/pressure/location2_raw_2016"
      - "examples/pressure/location2_raw_2017"
    link_folder: "examples/pressure/location2_raw_collected"
